---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: spring-petclinic-rest
spec:
  capacity:
    storage: 512Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /var/local/volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pulaumerah
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: spring-petclinic-rest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeName: pv
  storageClassName: local-storage
