---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: spring-petclinic-rest
  labels:
    environment: pulaumerah
data:
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
